config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sellers#index'

  mount ActionCable.server => '/cable'

  resources :sellers do
    collection do
      post :import
    end
  end

  resources :clients do
    collection do
      post :import
    end
  end

  resources :invoices do
    collection do
      get :change_status
    end
  end

  resources :invoice_elements
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :invoices
  
  validates :company_name, length: { in: 3..255 }, uniqueness: true
  validates :country, length: { in: 4..100 }
  validates :post_code, length: { in: 3..20 }
  validates :city, length: { in: 2..100 }
  validates :address_1, length: { in: 2..200 }
  validates :address_2, length: { in: 2..200 }, allow_blank: true
  validates :vat_number, length: { in: 5..50 }, uniqueness: true
  validates :prefix, length: { is: 2 }, uniqueness: true

  COLUMNS = [
    ['company_name', 0],
    ['country', 1],
    ['post_code', 2],
    ['city', 3],
    ['address_1', 4],
    ['address_2', 5],
    ['vat_number', 6],
    ['prefix', 7]
  ]
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action do
    add_breadcrumb(t('sellers.name'), '/sellers')
  end

  def index
    all_sellers
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(seller_params)
    all_sellers

    render action: :new unless @seller.save
  end

  def edit
    @seller = Seller.find_by_id(params[:id])
  end

  def update
    @seller = Seller.find_by_id(params[:id])
    all_sellers

    render action: :edit unless @seller.update_attributes(seller_params)
  end

  def destroy
    seller = Seller.find_by_id(params[:id])
    seller.destroy

    all_sellers
  end

  def import
    import_file_path = ImportService.new(params[:file]).call

    SellersImportWorker.perform_async(current_user.id, import_file_path,
                                      columns_data,
                                      params[:skip_first_row] == '1')
  end

  private

  def all_sellers
    @sellers = SellerDecorator.decorate_collection(
      Seller.order(:company_name).page(params[:page])
    )
  end

  def seller_params
    params.require(:seller).permit(:company_name, :country, :post_code, :city,
                                   :address_1, :address_2, :vat_number, :prefix)
  end

  def columns_data
    params.permit(:column_1, :column_2, :column_3, :column_4, :column_5,
                  :column_6, :column_7, :column_8).to_h.values.map(&:to_i)
  end
end

app/helpers/sellers_helper.rb
module SellersHelper
  def seller_columns_data_for_select
    Seller::COLUMNS.map do |column|
      [t("activerecord.attributes.seller.#{column[0]}"), column[1]]
    end
  end

  def sellers_ordered_by_company_name
    Seller.order(:company_name)
  end
end

app/views/sellers/create.js.erb
$('#form_content').slideUp(function() {
  $('#list_content').html('<%= j render('sellers/partials/sellers') %>')
  $('#pagination').html('<%= j render('sellers/partials/pagination') %>')
})

app/views/sellers/destroy.js.erb
$('#form_content').slideUp(function() {
  $('#list_content').html('<%= j render('sellers/partials/sellers') %>')
  $('#pagination').html('<%= j render('sellers/partials/pagination') %>')
})

app/views/sellers/edit.js.erb
if ($('#form_content').html().length && $('#form_content').is(":visible")) {
  $('#form_content').slideUp(function() {
    $(this).html('<%= j render('sellers/partials/edit') %>').slideDown();
  })
} else {
  $('#form_content').hide().html('<%= j render('sellers/partials/edit') %>').slideDown();
}

app/views/sellers/import.js.erb
$('#import_modal').modal('hide');
toastr.success('<%= t('sellers.import_pending') %>')
$('#modal_form').html('<%= j render('sellers/modals/form') %>')

app/views/sellers/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-5">
            <h4 class="card-title mb-0"><%= t('sellers.name') %></h4>
            <div class="small text-muted"><%= t('sellers.manage_info') %></div>
          </div>
          <div class="col-sm-7 d-none d-md-block">
            <%= link_to raw(%Q(<i class="icon-plus"></i> #{t('sellers.new')})), new_seller_path, class: "btn btn-success float-right", remote: true %>
            <button class="btn btn-primary float-right mr-2" type="button" data-toggle="modal" data-target="#import_modal">
              <i class="icon-layers"></i> <%= t('sellers.import') %>
            </button>
          </div>
        </div>
        <div style="margin-top:30px;">
          <div id="list_content"><%= render 'sellers/partials/sellers' %></div>
        </div>
      </div>
      <% unless @sellers.blank? || @sellers.total_pages == 1 %>
        <div class="card-footer">
          <div id="pagination"><%= render 'sellers/partials/pagination' %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render 'sellers/modals/import' %>

app/views/sellers/index.js.erb
$('#list_content').html('<%= j render('sellers/partials/sellers') %>')
$('#pagination').html('<%= j render('sellers/partials/pagination') %>')

app/views/sellers/new.js.erb
if ($('#form_content').html().length && $('#form_content').is(":visible")) {
  $('#form_content').slideUp(function() {
    $(this).html('<%= j render('sellers/partials/new') %>').slideDown();
  })
} else {
  $('#form_content').hide().html('<%= j render('sellers/partials/new') %>').slideDown();
}

app/views/sellers/update.js.erb
$('#form_content').slideUp(function() {
  $('#list_content').html('<%= j render('sellers/partials/sellers') %>')
  $('#pagination').html('<%= j render('sellers/partials/pagination') %>')
})