config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sellers#index'

  mount ActionCable.server => '/cable'

  resources :sellers do
    collection do
      post :import
    end
  end

  resources :clients do
    collection do
      post :import
    end
  end

  resources :invoices do
    collection do
      get :change_status
    end
  end

  resources :invoice_elements
end

app/models/invoice_element.rb
class InvoiceElement < ApplicationRecord
  include InvoiceData

  belongs_to :invoice

  validates :item_name, length: { in: 3..100 }
  validates :description, length: { in: 10..255 }, allow_blank: true
  validates :price, presence: true,
                    numericality: { greater_than: 0, less_than: 10_000 },
                    format: { with: /\A\d{1,6}(\.\d{0,2})?\z/ }
  validates :quantity, length: { in: 1..100 }

  after_create :recalculate_invoice
  after_destroy :recalculate_invoice

  private

  def recalculate_invoice
    invoice_recalculate(invoice)
  end
end

app/controllers/invoice_elements_controller.rb
class InvoiceElementsController < ApplicationController
  def new
    @invoice_element = InvoiceElement.new
  end

  def create
    @invoice_element = InvoiceElement.new(invoice_element_params)
    @invoice = InvoiceDecorator.decorate(@invoice_element.invoice)
    all_invoice_elements

    unless @invoice_element.save
      render action: :new
      return
    end

    @invoice_element = InvoiceElement.new
  end

  def destroy
    invoice_element = InvoiceElement.find_by_id(params[:id])
    @invoice = InvoiceDecorator.decorate(invoice_element.invoice)

    invoice_element.destroy

    @invoice_element = InvoiceElement.new
  end

  private

  def all_invoice_elements
    @invoice_elements = InvoiceElement.all
  end

  def invoice_element_params
    params.require(:invoice_element).permit(:invoice_id, :item_name,
                                            :description, :price, :quantity)
  end
end

app/views/invoice_elements/partials/_invoice_elements.html.erb
<%= form_with model: @invoice_element do |form| %>
  <%= form.hidden_field :invoice_id, value: @invoice.id %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="center">#</th>
        <th><%= t('invoice_elements.item') %></th>
        <th><%= t('invoice_elements.description') %></th>
        <th class="right"><%= t('invoice_elements.unit_cost') %></th>
        <th class="center"><%= t('invoice_elements.quantity') %></th>
        <th class="right"><%= t('invoice_elements.total') %></th>
        <% if @invoice.status.zero? %>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @last_index = 0 %>
      <% @invoice.invoice_elements.each_with_index do |invoice_element, index| %>
        <% @last_index = index + 1 %>
        <tr>
          <td class="center"><%= @last_index %></td>
          <td class="left strong"><%= invoice_element.item_name %></td>
          <td class="left"><%= invoice_element.description %></td>
          <td class="right"><%= number_to_currency invoice_element.price, unit: "£" %></td>
          <td class="center"><%= invoice_element.quantity %></td>
          <td class="right"><%= number_to_currency invoice_element.cost, unit: "£" %></td>
          <% if @invoice.status.zero? %>
            <td>
              <%= link_to raw(%Q(<i class="fa fa-trash"></i> #{t('delete')})), invoice_element_path(invoice_element), class: "btn btn-outline-danger btn-sm", method: :delete, remote: true, data: {confirm: t('confirm')} %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
    <% if @invoice.status.zero? %>
      <tfoot>
        <%= render 'invoice_elements/partials/new', form: form %>
      </tfoot>
    <% end %>
  </table>
<% end %>

app/views/invoice_elements/partials/_new.html.erb
<tr>
  <td><%= @last_index + 1 %></td>
  <td><%= form.text_field :item_name, class: 'form-control', placeholder: t('invoice_elements.item') %></td>
  <td><%= form.text_field :description, class: 'form-control', placeholder: t('invoice_elements.description') %></td>
  <td><%= form.text_field :price, class: 'form-control', placeholder: t('invoice_elements.unit_cost') %></td>
  <td><%= form.number_field :quantity, class: 'form-control', placeholder: t('invoice_elements.quantity'), min: 1, max: 9999999 %></td>
  <td><%= form.submit t('submit'), class: 'btn btn-primary' %></td>
  <% if @invoice.status.zero? %>
    <td></td>
  <% end %>
</tr>