config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sellers#index'

  mount ActionCable.server => '/cable'

  resources :sellers do
    collection do
      post :import
    end
  end

  resources :clients do
    collection do
      post :import
    end
  end

  resources :invoices do
    collection do
      get :change_status
    end
  end

  resources :invoice_elements
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :invoices
  
  validates :company_name, length: { in: 3..255 }, uniqueness: true
  validates :country, length: { in: 4..100 }
  validates :post_code, length: { in: 3..20 }
  validates :city, length: { in: 2..100 }
  validates :address_1, length: { in: 2..200 }
  validates :address_2, length: { in: 2..200 }, allow_blank: true
  validates :vat_number, length: { in: 5..50 }, uniqueness: true
  validates :prefix, length: { is: 2 }, uniqueness: true

  COLUMNS = [
    ['company_name', 0],
    ['country', 1],
    ['post_code', 2],
    ['city', 3],
    ['address_1', 4],
    ['address_2', 5],
    ['vat_number', 6],
    ['prefix', 7]
  ]
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action do
    add_breadcrumb(t('sellers.name'), '/sellers')
  end

  def index
    all_sellers
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(seller_params)
    all_sellers

    render action: :new unless @seller.save
  end

  def edit
    @seller = Seller.find_by_id(params[:id])
  end

  def update
    @seller = Seller.find_by_id(params[:id])
    all_sellers

    render action: :edit unless @seller.update_attributes(seller_params)
  end

  def destroy
    seller = Seller.find_by_id(params[:id])
    seller.destroy

    all_sellers
  end

  def import
    import_file_path = ImportService.new(params[:file]).call

    SellersImportWorker.perform_async(current_user.id, import_file_path,
                                      columns_data,
                                      params[:skip_first_row] == '1')
  end

  private

  def all_sellers
    @sellers = SellerDecorator.decorate_collection(
      Seller.order(:company_name).page(params[:page])
    )
  end

  def seller_params
    params.require(:seller).permit(:company_name, :country, :post_code, :city,
                                   :address_1, :address_2, :vat_number, :prefix)
  end

  def columns_data
    params.permit(:column_1, :column_2, :column_3, :column_4, :column_5,
                  :column_6, :column_7, :column_8).to_h.values.map(&:to_i)
  end
end

app/helpers/sellers_helper.rb
module SellersHelper
  def seller_columns_data_for_select
    Seller::COLUMNS.map do |column|
      [t("activerecord.attributes.seller.#{column[0]}"), column[1]]
    end
  end

  def sellers_ordered_by_company_name
    Seller.order(:company_name)
  end
end

app/views/sellers/partials/_edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <strong><%= t('sellers.edit') %></strong>
      </div>
      <%= render 'sellers/partials/form' %>
    </div>
  </div>
</div>

app/views/sellers/partials/_form.html.erb
<%= error_messages_for(@seller) %>

<%= form_with model: @seller do |form| %>
  <div class="card-body">
    <div class="row">
      <div class="form-group col-sm-10">
        <%= form.label :company_name %>
        <%= form.text_field :company_name, class: 'form-control', placeholder: t('sellers.placeholders.company_name') %>
      </div>
      <div class="form-group col-sm-2">
        <%= form.label :prefix %>
        <%= form.text_field :prefix, class: 'form-control', placeholder: t('sellers.placeholders.prefix') %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-sm-8">
        <%= form.label :country %>
        <%= form.text_field :country, class: 'form-control', placeholder: t('sellers.placeholders.country') %>
      </div>
      <div class="form-group col-sm-4">
        <%= form.label :vat_number %>
        <%= form.text_field :vat_number, class: 'form-control', placeholder: t('sellers.placeholders.vat_number') %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-sm-8">
        <%= form.label :city %>
        <%= form.text_field :city, class: 'form-control', placeholder: t('sellers.placeholders.city') %>
      </div>
      <div class="form-group col-sm-4">
        <%= form.label :post_code %>
        <%= form.text_field :post_code, class: 'form-control', placeholder: t('sellers.placeholders.post_code') %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :address_1 %>
      <%= form.text_field :address_1, class: 'form-control', placeholder: t('sellers.placeholders.address_1') %>
    </div>
    <div class="form-group">
      <%= form.label :address_2 %>
      <%= form.text_field :address_2, class: 'form-control', placeholder: t('sellers.placeholders.address_2') %>
    </div>
  </div>
  <div class="card-footer">
    <%= form.submit t('submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/sellers/partials/_new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <strong><%= t('sellers.new') %></strong>
      </div>
      <%= render 'sellers/partials/form' %>
    </div>
  </div>
</div>

app/views/sellers/partials/_pagination.html.erb
<div class="row text-center">
  <%= paginate @sellers, theme: 'twitter-bootstrap-4' %>
</div>

app/views/sellers/partials/_sellers.html.erb
<div id="form_content"></div>
<% unless @sellers.blank? %>
  <table class="table table-responsive-sm table-bordered">
    <thead>
      <tr>
        <th><%= Seller.human_attribute_name :company_name %></th>
        <th><%= t('sellers.address') %></th>
        <th><%= Seller.human_attribute_name :vat_number %></th>
        <th><%= Seller.human_attribute_name :prefix %></th>
        <th style="width: 180px;"><%= t('actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @sellers.each do |seller| %>
        <tr>
          <td><%= seller.company_name %></td>
          <td><%= seller.full_address %></td>
          <td><%= seller.vat_number %></td>
          <td><%= seller.prefix %></td>
          <td>
            <%= link_to raw(%Q(<i class="fa fa-pencil"></i> #{t('edit')})), edit_seller_path(seller), class: "btn btn-outline-info btn-sm", remote: true %>
            <%= link_to raw(%Q(<i class="fa fa-trash"></i> #{t('delete')})), seller_path(seller), class: "btn btn-outline-danger btn-sm", method: :delete, remote: true, data: {confirm: t('confirm')} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-primary" role="alert"><%= t('sellers.empty', button_text: t('sellers.new')) %></div>
<% end %>