config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sellers#index'

  mount ActionCable.server => '/cable'

  resources :sellers do
    collection do
      post :import
    end
  end

  resources :clients do
    collection do
      post :import
    end
  end

  resources :invoices do
    collection do
      get :change_status
    end
  end

  resources :invoice_elements
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices

  validates :company_name, length: { in: 3..255 }, uniqueness: true
  validates :country, length: { in: 4..100 }
  validates :post_code, length: { in: 3..20 }
  validates :city, length: { in: 2..100 }
  validates :address_1, length: { in: 2..200 }
  validates :address_2, length: { in: 2..200 }, allow_blank: true
  validates :vat_number, length: { in: 5..50 }, uniqueness: true

  COLUMNS = [
    ['company_name', 0],
    ['country', 1],
    ['post_code', 2],
    ['city', 3],
    ['address_1', 4],
    ['address_2', 5],
    ['vat_number', 6]
  ]
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action do
    add_breadcrumb(t('clients.name'), '/clients')
  end

  def index
    all_clients
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    all_clients

    render action: :new unless @client.save
  end

  def edit
    @client = Client.find_by_id(params[:id])
  end

  def update
    @client = Client.find_by_id(params[:id])
    all_clients

    render action: :edit unless @client.update_attributes(client_params)
  end

  def destroy
    client = Client.find_by_id(params[:id])
    client.destroy

    all_clients
  end

  def import
    import_file_path = ImportService.new(params[:file]).call

    ClientsImportWorker.perform_async(current_user.id, import_file_path,
                                      columns_data,
                                      params[:skip_first_row] == '1')
  end

  private

  def all_clients
    @clients = ClientDecorator.decorate_collection(
      Client.order(:company_name).page(params[:page])
    )
  end

  def client_params
    params.require(:client).permit(:company_name, :country, :post_code, :city,
                                   :address_1, :address_2, :vat_number)
  end

  def columns_data
    params.permit(:column_1, :column_2, :column_3, :column_4, :column_5,
                  :column_6, :column_7).to_h.values.map(&:to_i)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_columns_data_for_select
    Client::COLUMNS.map do |column|
      [t("activerecord.attributes.client.#{column[0]}"), column[1]]
    end
  end

  def clients_ordered_by_company_name
    Client.order(:company_name)
  end
end

app/views/clients/partials/_clients.html.erb
<div id="form_content"></div>
<% unless @clients.blank? %>
  <table class="table table-responsive-sm table-bordered">
    <thead>
      <tr>
        <th><%= Client.human_attribute_name :company_name %></th>
        <th><%= t('clients.address') %></th>
        <th><%= Client.human_attribute_name :vat_number %></th>
        <th style="width: 180px;"><%= t('actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.company_name %></td>
          <td><%= client.full_address %></td>
          <td><%= client.vat_number %></td>
          <td>
            <%= link_to raw(%Q(<i class="fa fa-pencil"></i> #{t('edit')})), edit_client_path(client), class: "btn btn-outline-info btn-sm", remote: true %>
            <%= link_to raw(%Q(<i class="fa fa-trash"></i> #{t('delete')})), client_path(client), class: "btn btn-outline-danger btn-sm", method: :delete, remote: true, data: {confirm: t('confirm')} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-primary" role="alert"><%= t('clients.empty', button_text: t('clients.new')) %></div>
<% end %>

app/views/clients/partials/_edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <strong><%= t('clients.edit') %></strong>
      </div>
      <%= render 'clients/partials/form' %>
    </div>
  </div>
</div>

app/views/clients/partials/_form.html.erb
<%= error_messages_for(@client) %>

<%= form_with model: @client do |form| %>
  <div class="card-body">
    <div class="form-group">
      <%= form.label :company_name %>
      <%= form.text_field :company_name, class: 'form-control', placeholder: t('clients.placeholders.company_name') %>
    </div>
    <div class="row">
      <div class="form-group col-sm-8">
        <%= form.label :country %>
        <%= form.text_field :country, class: 'form-control', placeholder: t('clients.placeholders.country') %>
      </div>
      <div class="form-group col-sm-4">
        <%= form.label :vat_number %>
        <%= form.text_field :vat_number, class: 'form-control', placeholder: t('clients.placeholders.vat_number') %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-sm-8">
        <%= form.label :city %>
        <%= form.text_field :city, class: 'form-control', placeholder: t('clients.placeholders.city') %>
      </div>
      <div class="form-group col-sm-4">
        <%= form.label :post_code %>
        <%= form.text_field :post_code, class: 'form-control', placeholder: t('clients.placeholders.post_code') %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :address_1 %>
      <%= form.text_field :address_1, class: 'form-control', placeholder: t('clients.placeholders.address_1') %>
    </div>
    <div class="form-group">
      <%= form.label :address_2 %>
      <%= form.text_field :address_2, class: 'form-control', placeholder: t('clients.placeholders.address_2') %>
    </div>
  </div>
  <div class="card-footer">
    <%= form.submit t('submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clients/partials/_new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <strong><%= t('clients.new') %></strong>
      </div>
      <%= render 'clients/partials/form' %>
    </div>
  </div>
</div>

app/views/clients/partials/_pagination.html.erb
<div class="row text-center">
  <%= paginate @clients, theme: 'twitter-bootstrap-4' %>
</div>